### ISSUE TITLE
how to handle start transaction request

### ISSUE THREAD

**Issue by GauravGunjal43** [mikuso/ocpp-rpc#18]
This is the message from the client:
`server got StartTransaction from EVB-P20261797: {
  connectorId: 1,
  idTag: '04B0267AE05C87',
  timestamp: '2022-07-09T16:17:36Z',
  meterStart: 0,
  reservationId: 0
}`

I'm using this to handle it on the server side:
`client.handle('StartTransaction',({params})=>{
        console.log('server got StartTransaction from ${client.identity}:',params)
        return {idTagInfo:{status:"Accepted"},transactionId:"1234"}
         })`
but this throws an 'Internal error' on the client side

**Comment by shankantino** [comment]
Hi @GauravGunjal43 

I'm also getting the same internal server error, can you help me with how you fix it?
