### ISSUE TITLE
Can we integrate client side with Angular ?

### ISSUE THREAD

**Issue by AbbeYassine** [mikuso/ocpp-rpc#19]
Hi @mikuso,

We are working with the integration of ocpp in our project.

My question is can we use client side with angular using webSocket ?

Thanks.

**Comment by mikuso** [comment]
Sorry, this module is not suitable for browsers.

I don't believe there is currently a compelling use-case for writing this module to work with browsers (aside from performing some superficial testing).

Here are a few reasons why a browser implementation wouldn't be very good:

* Browser websockets cannot use HTTP auth or custom client-side certificates, so is not compatible with any OCPP security profile.
* Browser websockets cannot send any custom headers with their opening handshake.
* CORS prevents using browser websockets with non-cooperating OCPP servers.
* Browser websockets give no control over pings/pongs (unable to listen for, or set their frequency).
* A server implementation is impossible.

Instead, I would recommend you to implement your OCPP client in Node.js and then use something like socket.io to communicate between your angular app and the OCPP client.
