### ISSUE TITLE
Issue on the certificate.

### ISSUE THREAD

**Issue by rowellcodizal** [mikuso/ocpp-rpc#28]
Hi @mikuso ,

I am asking for help with the issue that I encounter when I am trying to move to another server.

I have the .pfx file from another server but when I try to use and change to https the created server, I always have this error.
![image](https://user-images.githubusercontent.com/87008494/211445244-35a1bc2b-a473-444d-99f9-687e61f5485c.png)

Do you have an idea how to fix this?

**Comment by rowellcodizal** [comment]
Additional question, when I try to use the http but instead of localhost I use the domain to connect I have the encounter the same error.?

**Comment by mikuso** [comment]
Does the .pfx include a private key? Could it be a CORS issue?

To be honest, this kind of question is outside of the scope for this module. You may have better luck asking on stackoverflow.
