### ISSUE TITLE
Is there an option to change the path prefix?

### ISSUE THREAD

**Issue by 333miiko** [mikuso/ocpp-rpc#33]
If I want to host it behind a URL like http://example.com/ocpp is this possible?

**Comment by mikuso** [comment]
Yes.

Out of the box, this module will create a standard Node.js [http.Server](https://nodejs.org/dist/latest-v19.x/docs/api/http.html#class-httpserver) when you call `sever.listen(port)`.  The server listens for websocket Upgrade request events and process them as OCPP RPC clients.  It will process upgrade requests for _**any**_ URL path.

If you wanted to restrict the path which can be used, you can do so within your auth handler, like so:
```js
server.auth((accept, reject, handshake) => {
    if (handshake.endpoint !== '/ocpp') {
        reject(404, `Endpoint path not found`);
    }

    // else, accept the incoming client
    accept();
});
```

Of course, you can use whatever HTTP server you like (e.g. express.js), or host it behind a reverse-proxy restricted to a certain path.  There are many ways you could achieve this.
