### ISSUE TITLE
How to connect octt with security profile 2 and 3?

### ISSUE THREAD

**Issue by nagess-abdollahi** [mikuso/ocpp-rpc#34]
hi 
When I use your application in the role (CSMS) to connect the second and third security profile, OCTT (OCPP test tool) gives an SSL handshake error. Can you help with this? How should the settings in OCTT be?

Thanks

**Comment by mikuso** [comment]
I don't have access to the OCTT as this is beyond my budget, but I assume the issue is not something specific to the OCTT.

Can you provide a short code sample which demonstrates what you have done so far?

**Comment by mikuso** [comment]
Closing this issue as no reply received.
