### ISSUE TITLE
The server doesn't connect with real charge point

### ISSUE THREAD

**Issue by YassineEddyb** [mikuso/ocpp-rpc#39]
Hello Mikuso thanks for this amazing project.

When connecting to the server from a simulator it works fine, But when trying to connect to a real Charge Station It doesn't work, even though they are in the same network and I used my IP address to connect to the server from the Charge Point website.

I tried to lunch the server with "0.0.0.0" but no result, but when trying the same thing on a python server it works.

**Comment by mikuso** [comment]
Hi Yassine,

Sounds like a tricky one to solve, but I'll do my best to help.

What make and model of charging station are you using? Would you be able to show me how this is configured? (perhaps a screenshot of the charger's OCPP configuration interface)

Does the charging station collect any logs which might hint as to the problem?

**Comment by mikuso** [comment]
If you have logs, please can you share them here. I think this would be the easiest way to diagnose this.

**Comment by YassineEddyb** [comment]
Hi sorry for the late reponse

I found the problem, I was trying to connect to the charge point using ethernet cable but the server was running on WSL which does not have access to the ethernet interface.

I ran the server from powershell directly and that solved the problem, thank you.

**Comment by mikuso** [comment]
Thanks for the follow-up. I'm glad you were able to figure out the problem. 👍
