### ISSUE TITLE
process crashes when erroneous response is received

### ISSUE THREAD

**Issue by mf-fujimori** [mikuso/ocpp-rpc#45]
I am sending and receiving the following message.
![image](https://github.com/mikuso/ocpp-rpc/assets/120232912/6ab5c1e8-0d10-436b-a118-17e22aef508a)

The error that occurs.
![image](https://github.com/mikuso/ocpp-rpc/assets/120232912/c914be13-0fec-4c58-b711-59bece887071)

After that the process will die.
I don't really want to use the following method, but is there any other way to prevent the process from crashing?
![image](https://github.com/mikuso/ocpp-rpc/assets/120232912/c05e09bb-dcdd-4266-af74-c605141a71b7)

**Comment by mikuso** [comment]
Sorry, I'm having difficulty understanding the context.

Are you using this module to implement a server, client, or both?

Is the application crashing when making a call? or when handling a request?

**Comment by mf-fujimori** [comment]
thank you for your reply.
Sorry for the confusion.

it's the other way around.

It occurs in the following steps.

1. Send message from server to client
2. Client sends wrong response
Then the server crashes.

**Comment by mikuso** [comment]
So, like this?

```js
server.on('client', async (cli) => {
  const response = await cli.call('TriggerMessage', {/*...*/}); // <-- throws Error ?
});
```

You can catch these errors like so:

```js
server.on('client', async (cli) => {
  try {
    const response = await cli.call('TriggerMessage', {/*...*/});
  } catch (err) {
    console.error(err); // handle error
  }
});
```
