### ISSUE TITLE
Do we actually need the RPCClient when making connection to the real Charging point device?

### ISSUE THREAD

**Issue by antino-pranshu** [mikuso/ocpp-rpc#47]
Since I am new to the OCPP and I am trying to build a central system with this library using a 3rd party charger (ABB Terra AC charger).
I was wondering if we actually need the RPCClient when trying to connect with the real Charging Point device. I was assuming that the RPCClient is used for only simulation purpose. Can anyone confirm on this, or do we actually need the RPCClient while handshaking with real Charging Point?

**Comment by mikuso** [comment]
If you are only planning to implement a central system, then you won't need to instantiate any RPCClient instances.  Charging stations have their own software (with something akin to a RPCClient) which will connect to your central system.

You are right that you can use the RPCClient to make a simulator, but it's also possible to use it to make a real charging station too.
