### ISSUE TITLE
Unable to set chargingProfileKind.

### ISSUE THREAD

**Issue by Seekay369** [mikuso/ocpp-rpc#51]
const chargingProfile = {
        chargingProfileId: 1,
        stackLevel: 1,
        chargingSchedule: [
            {
                startPeriod: 0,
            },
            {
                startPeriod: 10,
            },
        ],
        chargingProfileKind: ocpp.ChargingProfileKind.Relative,
        ChargingProfilePurposeType: ocpp.ChargingProfilePurposeType.TxProfile
    };
    
    Kindly help how to set chargingProfileKind to Relative? Can it be string "Relative"?

**Comment by mikuso** [comment]
I'm not sure if you're in the right place. `ocpp.ChargingProfileKind` is not an export defined by this library.

Can you provide more context?

**Comment by Seekay369** [comment]
Sorry that I provide not enuf information.
For my situation, I want to set chargingProfile in RemoteStartTransaction.req.
According to OCPP1.6 protocol, We are able to set chargingPoint.

<img width="963" alt="Screenshot 2023-07-17 at 8 32 56 PM" src="https://github.com/mikuso/ocpp-rpc/assets/105281359/951c3cb6-3da6-4c00-b879-ec08ea79da40">


<img width="738" alt="Screenshot 2023-07-17 at 8 33 44 PM" src="https://github.com/mikuso/ocpp-rpc/assets/105281359/9bec9ebd-657f-4e01-bd5e-7ffb665dfd4f">
Inside the chargingProfile consist of chargingProfilePurpose, chargingProfileKind, chargingSchedule which is required field.

My question is how to set chargingProfilePurpose, chargingProfileKind, chargingSchedule by using this library.
Below are my code.

async function startChargingWithProfile(clientId) {
    const chargingProfile = {
        chargingProfileId: 1,
        stackLevel: 1,
        chargingProfileKind: 'Relative',
        chargingProfilePurposeType: 'TxProfile'
    };
    console.log('Received start charging');
    console.log('Client ID: ' + clientId);
    const sampleClient = clients.get(clientId);
    console.log('Sample Client: ' + sampleClient);
    if (sampleClient) {
        const response = await sampleClient.call('RemoteStartTransaction', {
            connectorId: 1, // start on connector 1
            idTag: 'seekaypersonal', // using an idTag with identity 'XXXXXXXX'
            chargingProfile: chargingProfile,
        });

        if (response.status === 'Accepted') {
            console.log('Remote start worked!');
        } else {
            console.log('Remote start rejected.');
        }

        return response.status;
    }
    else {
        return 'Client is not available.'
    }
}

**Comment by mikuso** [comment]
> My question is how to set chargingProfilePurpose, chargingProfileKind, chargingSchedule by using this library.

There are no enum-like constants - you simply need to write the string values.

**Comment by Seekay369** [comment]
is this okay if I set chargingProfileKind to 'Relative' and 'TxProfile' in string value?
Because it is not allow me to specify the start time and duration of the charging schedule relative to the start of the transaction, eventhrough the transaction is sucess.

`async function startChargingWithProfile(clientId) {
    
    const chargingSchedulePeriod = {
        startPeriod: 0,
        limit: 8.1,
    }
    
    const chargingSchedule = {
        duration: 60,
        chargingRateUnit: 'W',
        chargingSchedulePeriod: [
            chargingSchedulePeriod
        ]
    }

    const chargingProfile = {
        chargingProfileId: 1,
        stackLevel: 1,
        chargingProfileKind: 'Relative',
        chargingProfilePurposeType: 'TxProfile',
        chargingSchedule: chargingSchedule,
    };
    
    const sampleClient = clients.get(clientId);
    if (sampleClient) {
        const response = await sampleClient.call('RemoteStartTransaction', {
            connectorId: 1, // start on connector 1
            idTag: 'seekaypersonal', // using an idTag with identity 'XXXXXXXX'
            chargingProfile: chargingProfile,
        });

        if (response.status === 'Accepted') {
            console.log('Remote start with profile worked!');
        } else {
            console.log('Remote start with profile rejected.');
        }

        return response.status;
    }
    else {
        return 'Client is not available.'
    }
}`

**Comment by Seekay369** [comment]
Thanks for explaining all these. Appreciated.
