### ISSUE TITLE
Backend to OCPP server communication via WebSocket (sendRaw)

### ISSUE THREAD

**Issue by ease** [mikuso/ocpp-rpc#66]
I'd like to send some data from my own backend (NodeJS on Express) to `RPCServer`, is it recommended to use:
- `sendRaw` - https://github.com/mikuso/ocpp-rpc#clientsendrawmessage via WebSocket

or some other approach? 

e.g. registering handlers that are non-standard to OCPP specification, so e.g. having:
- `client.handle('MyOwnCall', ({params}) => {})` on the backend side and then calling it from the client with `client.call('MyOwnCall', {data: someDataIWantToPassToOCPP})`

In order to handle multiple actions between the charger and the central system, I'd like to be able to fully manage a charger.
@mikuso could you please provide an example? I'd want to catch the events on the OCPP server for each client.

Thanks for this great library.

**Comment by mikuso** [comment]
Hi @ease 

Is the express server instance and RPCServer instance part of the same application? Or is the express server running in one application and the RPCServer running in the other?

You _can_ use this module for implementing RPC between different applications, although I suspect this may not be what you need.

**Comment by ease** [comment]
It's the latter -> express server running in one application and the RPCServer running in the other.

Since client identity and RP server instance is important to me, what would you recommend for express server to RPCServer communication? If it wasn't this library and doing it via WebSockets (e.g. `ws`) we'd just emit event from express and listen to it on the WebSocket server. Here I'm trying to do the same in a correct way using your library and hoping to get some guidance on how to do it properly and what could be the right method I should use? How can I access the underlying socket and send events from the backend to RPCServer? I thought it's `sendRaw` as mentioned above.

Thanks for the quick response.

**Comment by mikuso** [comment]
If you wanted to send messages to an RPCServer, then you'd be best to use an RPCClient. There's no reason to use `sendRaw` unless you're doing some low-level debugging of the protocol.

You can create an RPCClient instance alongside your express app and have it connect to your existing RPCServer using a custom protocol. This would allow you to re-use the RPCServer to serve both your OCPP chargepoints and your custom RPC protocol at the same time.

**Comment by ease** [comment]
Yeah that makes sense and I've managed to pass the data using a custom protocol, but the issue I have with that is that I have a single reference to the `client` in 
```
server.on('client', (client) => {
    // Here, I'll have a reference to the RPCClient which is my express app, but I'd also like to have 
    // the ability to talk to charger that'd also be connected to this server

    // I'd like to catch the event from the custom protocol (from backend) here and pass it to the 
    // charger to perform `.call` on the charger, not on the RPCClient which is my express backend.
})
```

How to achieve getting both express's client reference and real charger's client reference?

**Comment by mikuso** [comment]
A common way to reference different clients is by their differing identities - but you'd need to create this index yourself as the library doesn't include this as a feature.

[Here's an example](https://github.com/mikuso/ocpp-rpc/issues/26#issuecomment-1380034985) of how I've done this before.

You could then reference your different clients like so:

```js
clients.get('ExpressServer').send(/* something */);
clients.get('Charger').send(/* something */);
```

**Comment by ease** [comment]
Thanks, I had that in mind and I'm around the same idea of using identities. I've noticed you're storing each new client under the private property (`_clients`) so I was thinking that I've missed something in your docs about that Map being exposed somewhere and just wanted to check.

Thanks for the suggestions, I think you can close this now.

**Comment by mikuso** [comment]
Ah, I see.

The main reason why this library doesn't index the clients for you is because there are so many different ways in which you might want to do it. You could easily find yourself in a situation where you have multiple clients connecting with the same (duplicate) identities, but differing protocols, paths, "virtual" hosts, etc...

Anyway, I'm glad this solution works for your case. Thanks.
