### ISSUE TITLE
Disconnects after 30 sec

### ISSUE THREAD

**Issue by tmb-01** [mikuso/ocpp-rpc#72]
It works fine on my local machine but when I deploy it to my VPS, WS disconnects after 30 sec. 

<img width="530" alt="Screenshot 2024-03-13 at 16 08 49" src="https://github.com/mikuso/ocpp-rpc/assets/55913644/f62a4679-2181-46f6-b856-e9d24f41e4c8">

I thought I had a limitation in my VPS for WS but my other WS is working fine.

I am using this simulator.
https://lamerat.github.io/OCPP-Charge-Point-Simulator/

**Comment by tmb-01** [comment]
@mikuso Can you help me to solve this problem?

**Comment by mikuso** [comment]
Try listening on the RPCServerClient instance for the `'socketError'` and `'close'` events and log what happens.

Do you get a socket error event?
Do you get a close event? If so, what close code & reason are you given?

**Comment by tmb-01** [comment]
when I start it with pm2, I face this error, but when I start it with node it works fine. But I cant use node to run in background.
