### ISSUE TITLE
Getting Client Identity from the URL and not from the handshake.identity

### ISSUE THREAD

**Issue by neeact** [mikuso/ocpp-rpc#79]
Hello!

I'm having the following problem, not sure if you can help:

some OCPP devices when connecting to the server are showing an empty handshake.identity.

I understand that some devices set their OCPP identity directly in the OCPP Server Endpoint URL - i.e.:

if OCPP server URL is "ws://myocppserver.dummycom", they point the Client Device to "ws://myocppserver.dummycom/A12345", being "A12345" the intended device identity.

How can I get the Client Device Identity from the server address in alternative (or in addition) to the handshake.identity?

Any help is much appreciated!
Thank you.

**Comment by gareth3wm** [comment]
Hi @neeact 

By definition (as per the OCPP docs), the device identity is basically just the tail of the path of the websocket URL.

Is there a different scenario you've encountered in the wild?

**Comment by mikuso** [comment]
Hi @neeact 

By definition (as per the OCPP docs), the device identity is basically just the tail of the path of the websocket URL.

Is there a different scenario you've encountered in the wild?

**Comment by neeact** [comment]
Okay, I have just found out (was not aware) that in the handshake information the "endpoint" is also filled and it contains this information - example of a handshake payload:

```
(...)
3|ksocpp  |   protocols: Set(1) { 'ocpp1.6' },
3|ksocpp  |   endpoint: '/**A12345**',
3|ksocpp  |   identity: '1523390420',
3|ksocpp  |   query: URLSearchParams {},
(...) 
```

So I can get the Client identity from the handshake.endpoint.

Thank you!

**Comment by neeact** [comment]
Closing this (non) issue :)

**Comment by mikuso** [comment]
Ah, ok. Perfect. 👍
